# Site settings
title: KoalaCoin
description: The first coin with free giveaways
baseurl: ""
url: "http://koalacoin.money"

# User settings
username: KoalaCoin
user_title_1: "The ultimate animal based coin"
user_title_2: "The first coin with free giveaways"
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
reddit_link: https://www.reddit.com/r/KoalaCoin/
pancake_link: https://pancakeswap.finance/swap?outputCurrency=0xe75d9c2b47baec78b9778be72cddc59ead3a69b8
bscscan_link: https://bscscan.com/token/0xe75d9c2b47baec78b9778be72cddc59ead3a69b8

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
